### ISSUE TITLE
Error: Dependency package(s) 'matlib' not available.

### ISSUE THREAD

**Issue by FlorianSeitz** [JanaJarecki/cognitivemodels#26]
After merging your changes into my feature/test branch, I received the following error when conducting devtools::load_all().

Error: Dependency package(s) 'matlib' not available.

Maybe matlib should be installed directly when loading cogscimodels?

**Comment by JanaJarecki** [comment]
Please download the development version of matlib here https://github.com/friendly/matlib this should fix the bug.

(there was a bug in matlib which broke some of our code, it has been fixed by the very great developers of matlib almost immediately, but they have not yet published the new package version on cran)

@JanaJarecki > add this to the README file

**Comment by JanaJarecki** [comment]
Is this fixed for you? Did you have to download the matlib package from github?

**Comment by JanaJarecki** [comment]
Fixed by matlib cran update
